version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: loopint-postgres
    environment:
      POSTGRES_DB: loopint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: loopint-api
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/loopint
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    container_name: loopint-web
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  postgres_data: